swagger: '2.0'
info:
  description: |
    サポーターズ勉強会で使用するサンプルのAPIです
  version: 1.0.0
  title: Supporterz API
schemes:
- http
produces:
- application/json
basePath: "/api"
paths:
  '/v1/users':
    get:
      tags:
      - Supporterz
      description: ユーザーの一覧
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/SwUserListResponse'
    post:
      tags:
      - Supporterz
      description: ユーザーの追加
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/SwAddUser'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/SwPostResponse'
  '/v1/users/{id}':
    get:
      tags:
      - Supporterz
      description: ユーザーの詳細
      parameters:
        - name: id
          in: path
          description: ユーザーID
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/SwUserResponse'
    put:
      tags:
      - Supporterz
      description: ユーザーの編集
      parameters:
        - name: id
          in: path
          description: ユーザーID
          required: true
          type: integer
          format: int64
        - name: body
          in: body
          schema:
            $ref: '#/definitions/SwAddUser'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/SwPostResponse'
    delete:
      tags:
      - Supporterz
      description: ユーザーの削除
      parameters:
        - name: id
          in: path
          description: ユーザーID
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/SwPostResponse'
definitions:
  SwUserListResponse:
    type: object
    required:
    - users
    properties:
      users:
        type: array
        items:
          $ref: '#/definitions/SwUserListRow'
  SwUserListRow:
    required:
    - id
    - name
    - email
    properties:
      id:
        type: integer
      name:
        type: string
      email:
        type: string
  SwUserResponse:
    type: object
    required:
    - id
    - name
    - email
    properties:
      id:
        type: integer
      name:
        type: string
      email:
        type: string
  SwAddUser:
    type: object
    required:
      - name
      - email
    properties:
      name:
        type: string
      email:
        type: string
  SwPostResponse:
    type: object
    required:
      - status
    properties:
      status:
        type: string
